export type Problem = {
	id: string;
	title: string;
	difficulty: string;
	category: string;
	order: number;
	videoId?: string;
	likes:number,
	dislikes: 0,
	link?: string,
};


export const problems: Problem[] = [
	{
		id: "two-sum",
		title: "1. Two Sum",
		difficulty: "Easy",
		category: "Array",
		order: 1,
		videoId: "8-k1C6ehKuw",
		likes: 0,
		dislikes: 0,
		link: "",
		
	},
	{
		id: "reverse-linked-list",
		title: "2. Reverse Linked List",
		difficulty: "Hard",
		category: "Linked List",
		order: 2,
		videoId: "",
		likes: 0,
		dislikes: 0,
		link: "",
		
	},
	{
		id: "jump-game",
		title: "3. Jump Game",
		difficulty: "Medium",
		category: "Dynamic Programming",
		order: 3,
		videoId: "",
		likes: 0,
		dislikes: 0,
		link: "",
	},
	{
		id: "valid-parentheses",
		title: "4. Valid Parentheses",
		difficulty: "Easy",
		category: "Stack",
		order: 4,
		videoId: "xty7fr-k0TU",
		likes: 0,
		dislikes: 0,
		link: "",
	},
	{
		id: "search-a-2d-matrix",
		title: "5. Search a 2D Matrix",
		difficulty: "Medium",
		category: "Binary Search",
		order: 5,
		videoId: "ZfFl4torNg4",
		likes: 0,
		dislikes: 0,
		link: "",
	},
	{
		id: "container-with-most-water",
		title: "6. Container With Most Water",
		difficulty: "Medium",
		category: "Two Pointers",
		order: 6,
		videoId: "",
		likes: 0,
		dislikes: 0,
		link: "https://leetcode.com/problems/container-with-most-water/description/",
	},
	{
		id: "merge-intervals",
		title: "7. Merge Intervals",
		difficulty: "Medium",
		category: "intervals",
		order: 7,
		videoId: "",
		likes: 0,
		dislikes: 0,
		link: "https://leetcode.com/problems/merge-intervals/description/",
	},
	{
		id: "maximum-depth-of-binary-tree",
		title: "8. Maximum Depth of Binary Tree",
		difficulty: "Easy",
		category: "Tree",
		order: 8,
		videoId: "4qYTqOiRMoM",
		likes: 0,
		dislikes: 0,
		link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/",
	},
	{
		id: "best-time-to-buy-and-sell-stock",
		title: "9. Best Time to Buy and Sell Stock",
		difficulty: "Easy",
		category: "Array",
		order: 9,
		videoId: "",
		likes: 0,
		dislikes: 0,
		link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
	},
	{
		id: "subsets",
		title: "10. Subsets",
		difficulty: "Medium",
		category: "Backtracking",
		order: 10,
		videoId: "",
		likes: 0,
		dislikes: 0,
		link: "https://leetcode.com/problems/subsets/description/",
	},
];